added commands to check is resource exists on  , for testing only

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,15 +29,31 @@ jobs :
             - name: Terraform Init
               run : terraform init
 
-            - name: Import existing AWS resources
+            - name: Import existing AWS resources if they exist
               run: |
-                terraform import aws_s3_bucket.assign_bucket assignement-bucket-fadi7 || true
-                terraform import aws_iam_policy.lambda_s3_policy arn:aws:iam::992824239500:policy/lambda_s3_policy || true
-                terraform import aws_iam_role.assign_iam assign_iam || true
-                terraform import aws_iam_role_policy_attachment.test_attach assign_iam/arn:aws:iam::992824239500:policy/lambda_s3_policy || true
-                terraform import aws_lambda_function.s3_lambda list-s3-files || true
-                terraform import aws_lambda_permission.allow_s3 list-s3-files/AllowExecutionFromS3 || true
-                terraform import aws_sns_topic.assign_topic arn:aws:sns:eu-central-1:992824239500:user-notifications || true
+                # S3 Bucket
+                aws s3api head-bucket --bucket assignement-bucket-fadi7 2>/dev/null && \
+                terraform import aws_s3_bucket.assign_bucket assignement-bucket-fadi7 || echo "S3 bucket not found, will be created."
+
+                # IAM Policy
+                aws iam get-policy --policy-arn arn:aws:iam::992824239500:policy/lambda_s3_policy 2>/dev/null && \
+                terraform import aws_iam_policy.lambda_s3_policy arn:aws:iam::992824239500:policy/lambda_s3_policy || echo "Policy not found."
+
+                # IAM Role
+                aws iam get-role --role-name assign_iam 2>/dev/null && \
+                terraform import aws_iam_role.assign_iam assign_iam || echo "Role not found."
+
+                # Lambda
+                aws lambda get-function --function-name list-s3-files 2>/dev/null && \
+                terraform import aws_lambda_function.s3_lambda list-s3-files || echo "Lambda not found."
+
+                # Lambda permission (skip if Lambda doesnt exist)
+                terraform import aws_lambda_permission.allow_s3 list-s3-files/AllowExecutionFromS3 || echo "Permission import skipped."
+
+                # SNS Topic
+                aws sns get-topic-attributes --topic-arn arn:aws:sns:eu-central-1:992824239500:user-notifications 2>/dev/null && \
+                terraform import aws_sns_topic.assign_topic arn:aws:sns:eu-central-1:992824239500:user-notifications || echo "SNS topic not found."
+
 
             - name: Terraform Apply
               run: terraform apply -auto-approve
